### PR TITLE
feat(transform): Adds yaml transformer

### PR DESCRIPTION
**Pull request by kenjones-cisco**
Provides the ability to use yaml based configuration files.

Also a bit of an overhaul of some of the project parts to support
testing etc. on Windows. Also reduced errors where defaults could
easily be provided to support a better experience.

### CODE REVIEW

**Comment by kenjones-cisco** [comment]
Feel free to reject the pull request as I know there are more changes than you might normally expect within a feature but most of the changes were for something I'm considering since many of the config management solutions available do not work well for submodules while still allow the end consumer to actually provide configurations if/when they want to.

Just wanted to share and provide the option to use the changes if you wanted them.

The CI failure is related to Node 0.10.x. I'm a bigger fan of Node 4.2.x LTS so I rarely check or build for it.

**Comment by rjz** [comment]
@kenjones-cisco, thanks for this! Lots of good stuff here, and YAML's definitely been on the list for some time. A couple thoughts:
1. With respect to submodules (or npm `dependencies`), would keeping YAML support in a separate package (`confab-yaml`) complicate the workflow you have in mind? If that's a possibility, we could definitely add README / documentation references here to help folks opt-in to YAML support as needed.
2. Either way, Windows-safe gulp tasks are a great introduction. Even if we separate the YAML feature, I'd love to get these merged in.
3. Defaults. The throw-first mindset is intended to make incomplete or invalid configs blindingly obvious to the dev (i.e., minimize silent errors). All ears on changing this in the name of ease-of-use, but not sure we want to loosen restrictions on whatever config structure is prescribed.
4. Node 0.10 support: I'm aware of at least a few projects still using versions before the 4.0 release that may or may not be locked to the current npm package. Since the issue seems to just be the missing `debuglog` util, we could either [polyfill](https://github.com/sam-github/node-debuglog) or just use `console.error`

Thanks again, and looking forward to your thoughts!

**Comment by kenjones-cisco** [comment]
``` javascript
var debuglog = require('debuglog')('confab'), 
     tryRequire  = require('tryrequire'),
      yaml = tryRequire('js-yaml');

if (yaml) {
  transforms.loadYaml = function (files) {
    return load(files, yaml.safeLoad);
  };
} else {
  debuglog('js-yaml not installed; loadYaml transformer');
```
1. Maybe look at optional features doing something like above. This makes the dependencies something the users of confab would need to include for the features they want to include. Otherwise a plugin-style pattern could work as well (not come across a really good and simple one like those I've used in python in the past).
2. :+1: 
3. Maybe `confab(transforms, options)` where options provides either `silentErrors` or `withErrors` and choose name based on whether throw first or no throw as the default. Some of the defaulting is done to avoid getting a random TypeError or other obscure error vs. a specific error that informs the user of what is wrong and so they know what to do. I'm flexible as long as random obscure errors can be avoided :smile: 
4. As seen in the example, doing a simple require('debuglog') works fine. If support 0.10.x is needed.

Do you have a Roadmap or plans for confab?

On a side note:
- include optional `Config` class/object that provides `get`, `has`, `clone`, `reset`.
- another transformer `loadEnvConfigFile` which will basically attempts to identify a configuration file based on the current runtime information (NODE_ENV, NODE_APP_INSTANCE, HOST || HOSTNAME) as a convenience for users to avoid having to specifying the configuration file but driven on the runtime. (Similar to this https://github.com/lorenwest/node-config/wiki/Configuration-Files)

Got the code working as expected but need to write the test cases first before I commit.

**Comment by kenjones-cisco** [comment]
After the last commit only the item 3 is not completed. I do need to add the docs part for the new components but figured I'd take additional feedback before getting too much deeper.

Simple example using the `Config`:

``` javascript
'use strict';

var confab = require('./');

var cfg = confab.create([
    confab.assign({
        a: 1,
        b: 2,
        c: 3
    })
]);

console.log(cfg.clone());
console.log(cfg.get('a'));
console.log(cfg.get('x'));
```

**Comment by rjz** [comment]
debuglog, #2: awesome.

> I'm flexible as long as random obscure errors can be avoided

Absolutely, and great point. Throwing deliberate (but useful) errors would stick with the idiom, though if there's a use-case motivating the opt-out (`silentErrors` or otherwise), no problem here.

> Maybe look at optional features doing something like above. This makes the dependencies something the users of confab would need to include for the features they want to include.

I'm a little hesitant on this one, as it breaks with the emphasis on explicit, declarative configuration. I'm not sure we add much complexity (outside an extra `dependency`) by just documenting other ecosystem modules and adding them on-demand—something like:

```
var confab = require('confab');
var loadYaml = require('confab-yaml');

module.exports = confab([
  loadYaml('/path/to.yml'),
  // ...
]);
```

Similarly, something like `Config` or `loadEnvConfigFile` could be published as separate, opt-in modules (linked / detailed in the readme / docs site).

I guess the bigger question is, 'what should core support entail?' It's so far been restricted to 'things node supports natively', but maybe there's a case to expand to include batteries for common tasks beyond that. And on that note...

> Do you have a Roadmap or plans for confab?

Nothing formal—very much an 'expand as needed / requested'. Very open to changing this, though: perhaps this is a good time to document expectations between the core and (potentially) ecosystem libraries?

**Comment by kenjones-cisco** [comment]
So the remaining features, I added to https://github.com/kenjones-cisco/confab-addons

Is this closer to what you were thinking?

**Comment by rjz** [comment]
> Is this closer to what you were thinking?

Works for me! Unless there's a reason not to, I'll add the additional filters to the README here and look forward to opt-in YAML and getter/setter support.

Thanks again, @kenjones-cisco!

**Pull request closed without merging**
